# Generated by Django 5.0 on 2025-12-30 17:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance in Toman', max_digits=12)),
                ('total_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount charged', max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount spent', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Account',
                'verbose_name_plural': 'Credit Accounts',
                'db_table': 'credit_accounts',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('deduct', 'Deduct'), ('refund', 'Refund')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Balance before transaction', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Balance after transaction', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID (e.g., SMS message ID)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='credits.creditaccount')),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='credit_tran_account_cc200b_idx'), models.Index(fields=['reference_id'], name='credit_tran_referen_214bea_idx')],
            },
        ),
    ]
