from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS credit_transactions CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        ),

        migrations.RunSQL(
            sql="""
                CREATE TABLE credit_transactions
                (
                    id               bigint GENERATED BY DEFAULT AS IDENTITY,
                    account_id       bigint                   NOT NULL,
                    transaction_type varchar(10)              NOT NULL,
                    amount           numeric(12, 2)           NOT NULL,
                    balance_before   numeric(12, 2)           NOT NULL,
                    balance_after    numeric(12, 2)           NOT NULL,
                    description      text                     NOT NULL,
                    reference_id     varchar(100)             NOT NULL,
                    created_at       timestamp with time zone NOT NULL,
                    PRIMARY KEY (id, created_at)
                ) PARTITION BY RANGE (created_at);
                """,
            reverse_sql="DROP TABLE credit_transactions;"
        ),

        migrations.RunSQL(
            sql="""
                CREATE INDEX credit_tran_account_created_idx ON credit_transactions (account_id, created_at DESC);
                CREATE INDEX credit_tran_reference_idx ON credit_transactions (reference_id);
                """,
            reverse_sql=migrations.RunSQL.noop
        ),

        migrations.RunSQL(
            sql="""
                CREATE TABLE credit_transactions_default PARTITION OF credit_transactions DEFAULT;

                CREATE TABLE credit_transactions_2025 PARTITION OF credit_transactions
                    FOR VALUES FROM
                (
                    '2025-01-01 00:00:00+00'
                ) TO
                (
                    '2026-01-01 00:00:00+00'
                );

                CREATE TABLE credit_transactions_2026 PARTITION OF credit_transactions
                    FOR VALUES FROM
                (
                    '2026-01-01 00:00:00+00'
                ) TO
                (
                    '2027-01-01 00:00:00+00'
                );
                """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]