# Generated by Django 5.0 on 2025-12-30 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(help_text='Recipient phone number', max_length=15)),
                ('message', models.TextField(help_text='SMS message text', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('express', 'Express')], default='normal', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of sending', max_digits=10)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled send time', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Actual send time', null=True)),
                ('failed_reason', models.TextField(blank=True, help_text='Failure reason')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'db_table': 'sms_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='sms_message_user_id_4b956f_idx'), models.Index(fields=['status', 'priority'], name='sms_message_status_50f9a4_idx'), models.Index(fields=['recipient'], name='sms_message_recipie_3ec58a_idx'), models.Index(fields=['scheduled_at'], name='sms_message_schedul_fc5139_idx')],
            },
        ),
    ]
