# Generated by Django 5.0 on 2025-12-31 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['user', 'status', '-created_at'], name='sms_message_user_id_45250c_idx'),
        ),
    ]
